// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQdZyMbYRtjmBKjTxkRHz9FTYuNcGL4PI',
    appId: '1:127987307044:web:3be2fc3feb187ca4e27eb1',
    messagingSenderId: '127987307044',
    projectId: 'infotour-869cd',
    authDomain: 'infotour-869cd.firebaseapp.com',
    storageBucket: 'infotour-869cd.appspot.com',
    measurementId: 'G-10LSLHW4CN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq5udKzf7PsRXzlOyBWBYrEJZ-DyWzPek',
    appId: '1:127987307044:android:08dc6653b4a14b45e27eb1',
    messagingSenderId: '127987307044',
    projectId: 'infotour-869cd',
    storageBucket: 'infotour-869cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8XBdQMfF0QDGxPu10z4JVir_kin_hWPs',
    appId: '1:127987307044:ios:303b8ebc83d2e3c2e27eb1',
    messagingSenderId: '127987307044',
    projectId: 'infotour-869cd',
    storageBucket: 'infotour-869cd.appspot.com',
    iosClientId: '127987307044-dl7nb2m53vncum77g3jhk0givvi99dtf.apps.googleusercontent.com',
    iosBundleId: 'com.bibary.tourInfo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8XBdQMfF0QDGxPu10z4JVir_kin_hWPs',
    appId: '1:127987307044:ios:303b8ebc83d2e3c2e27eb1',
    messagingSenderId: '127987307044',
    projectId: 'infotour-869cd',
    storageBucket: 'infotour-869cd.appspot.com',
    iosClientId: '127987307044-dl7nb2m53vncum77g3jhk0givvi99dtf.apps.googleusercontent.com',
    iosBundleId: 'com.bibary.tourInfo',
  );
}
